spring.application.name=api-geek-store

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT SECURITY
# ===============================
app.security.jwt.secret-key=${JWT_SECRET_KEY}
app.security.jwt.expiration-seconds=86400000
app.security.cookie.secure=false

# ===============================
# CLOUDINARY (IMAGES)
# ===============================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.folder.root=archive_uploads

# ===============================
# EMAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# MERCADO PAGO
# ===============================
mercadopago.access_token=${MP_ACCESS_TOKEN}

# ===============================
# GOOGLE AUTH
# ===============================
google.client.id=${GOOGLE_CLIENT_ID}

mail.from.address=${MAIL_USERNAME}


application.frontend.url=http://localhost:3000

#CAMBIAR EN PRODUCCION
#application.frontend.url=https://www.geekstore.com


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}



spring.mvc.problemdetails.enabled=true


app.security.token.expiration-minutes=15





# =====================================
# SWAGGER
# =====================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha